// Hidden niches: demand with evidence, few providers, and work Claude can do (research, Oct 2026).
// s = [demand, few competitors, Claude fit, beginner-friendly], each 1-5.
var NICHE_GROUPS = {
  rules:"Rules and deadlines",
  software:"Specialist software",
  backoffice:"Back office",
  data:"Data subscriptions",
  requests:"Things people ask for",
  aiera:"New AI needs",
  research:"Research and nonprofits",
  crossborder:"Cross-border selling"
};
var NICHES = [];

// --- Specialist software
NICHES.push(
{id:"access-rescue", group:"software", rank:101, s:[4,4,4,3],
 name:"Microsoft Access database rescue",
 short:"Keep old Access databases running, or move them to the web",
 who:"Small manufacturers, clinics, distributors, charities and councils whose Access database was built by someone who has since left.",
 need:"Fixes after Office updates, new reports, 64-bit VBA fixes, or moving the data into a proper database or a web app.",
 demand:"Access 2021 support ends on 13 October 2026, a year after Access 2016 and 2019. US Access/VBA work averages about $48 an hour (ZipRecruiter, Aug 2026), and London contracts have a median of £650 a day.",
 why:"Migration firms all report the same thing: the original builder has often retired, and VBA skills get harder to find every year.",
 price:"$150–600 per fix, $1,500–8,000 per migration",
 how:"Python tools (mdbtools, access-parser) read the tables here. The client exports forms and VBA as text so Claude can read every module. A web replacement can be built and fully tested in this sandbox; VBA changes have to be tested by the client on Windows.",
 where:"UtterAccess, Access World Forums, r/MSAccess, Microsoft Q&A, Upwork \"Microsoft Access\" jobs, and local IT-support firms that inherit these databases.",
 first:"Turn Microsoft's free Northwind sample database into a small web app, publish a before-and-after page, and offer a $99 \"Access health check\" to 15 job posts and 10 local IT firms.",
 risk:"These files hold personal data, so sign an NDA, work on copies and delete them afterwards. Never edit the live file."},
{id:"drupal7", group:"software", rank:102, s:[4,3,5,3],
 name:"Getting organisations off Drupal 7",
 short:"Upgrade, archive or migrate sites on an unsupported system",
 who:"Nonprofits (often using CiviCRM), university departments, associations and councils.",
 need:"A safe, affordable way off Drupal 7: upgrade to Backdrop (a Drupal 7 fork), freeze the site as static pages, or migrate to current Drupal, plus a malware check.",
 demand:"Drupal 7 support ended on 5 January 2025, yet about 134,000 sites reportedly still run it (unverified). Organisations pay for extended security support through the Drupal Association's paid program.",
 why:"Agencies price these moves at £4,000–35,000. Very little is offered at small-budget prices.",
 price:"$800–3,000 per fixed package (est.)",
 how:"Everything can be tested here: run a copy of the client's site in Docker, run Backdrop's upgrade or Drupal's migration, and compare old and new pages with Playwright screenshots. A static archive is just a crawl of the site.",
 where:"The CiviCRM community, Drupal Slack, university web teams, and sites whose page source still shows the \"Generator: Drupal 7\" tag.",
 first:"Move a sample Drupal 7 site to Backdrop and to a static archive here, write a one-page \"3 ways off Drupal 7\" PDF, and email 20 nonprofits still running it.",
 risk:"Many of these sites are already hacked, so scan copies before moving them. Only look at what a normal visit shows, and follow cold-email laws."},
{id:"autolisp", group:"software", rank:103, s:[3,4,4,3],
 name:"AutoCAD automation routines (AutoLISP)",
 short:"Small scripts that save drafters hours every week",
 who:"Small drafting, building-services, survey, civil and fabrication firms, and their CAD managers.",
 need:"Batch layer and block edits, auto-numbering, exporting attributes or coordinates to Excel, standard details and standards checks.",
 demand:"Autodesk's forums carry repeated \"hiring a LISP programmer\" threads, and ZipRecruiter lists AutoLISP jobs at $25–49 an hour (Jun 2026). AutoCAD LT gained AutoLISP in 2024, opening up its large base of cheaper users.",
 why:"Cad Crowd lists only 28 AutoLISP freelancers (Mar 2026). Forum volunteers write tiny routines for free, so sell bundles rather than one-liners.",
 price:"$50–300 per routine, $500–1,500 per project",
 how:"Claude writes AutoLISP well, and the Python ezdxf library builds and checks test drawings here. AutoCAD doesn't run on Linux, so the client does the final test (a BricsCAD trial works for a first check).",
 where:"The Visual LISP forum on forums.autodesk.com, CADTutor, TheSwamp, AUGI, Cad Crowd, Upwork \"AutoLISP\" jobs, CAD managers on LinkedIn.",
 first:"Publish 3 free routines that work in AutoCAD LT, answer 3 forum requests with them, and offer 15 CAD managers one custom routine for $99.",
 risk:"Don't reuse other people's copyrighted routines, and test only on copies of drawings."},
{id:"coldfusion", group:"software", rank:104, s:[3,5,4,2],
 name:"ColdFusion maintenance and moves to Lucee",
 short:"Keep 20-year-old business apps alive and secure",
 who:"Insurers, government bodies, universities and membership groups running old ColdFusion apps for billing, claims or licensing.",
 need:"Bug and security fixes, moving from paid Adobe ColdFusion to the free Lucee engine, upgrades and documentation.",
 demand:"Vendors report that many organisations still run mission-critical ColdFusion apps in 2026, and companies keep advertising ColdFusion roles.",
 why:"Ortus calls it a \"CFML talent crunch\": experienced developers are shrinking fast and many companies depend on a single developer.",
 price:"$60–125 an hour (est.)",
 how:"CommandBox and Lucee run on Linux, so a copy of the app runs here against a copy of its database. Claude fixes SQL injection, updates old tags and writes tests; Adobe-only features are tested on the client's staging server.",
 where:"CFML Slack, dev.lucee.org, Adobe's ColdFusion community, ColdFusion contracts on LinkedIn, Dice and Indeed.",
 first:"Move a small open-source ColdFusion app to the latest Lucee, publish the write-up, and send it to 10 organisations advertising ColdFusion roles.",
 risk:"Cautious buyers may ask for background checks or insurance. Say plainly that the work is AI-assisted and human-reviewed, and never test on the live system."},
{id:"catalogue", group:"software", rank:105, s:[3,3,4,4],
 name:"Spreadsheet-to-catalogue automation",
 short:"Print-ready product catalogues rebuilt from a spreadsheet",
 who:"Wholesalers, parts distributors, furniture and fashion brands, and print shops that produce seasonal price lists.",
 need:"A product spreadsheet and photos turned into a styled multi-page catalogue that can be re-run whenever prices change.",
 demand:"Adobe forum users keep asking how to automate catalogues from Excel, and a market of paid plugins exists for it (EasyCatalog, InData and others).",
 why:"InDesign's built-in Data Merge can't handle complex multi-page layouts, so the job needs scripting, which few designers do.",
 price:"$300–2,500 per setup, plus a fee per new edition (est.)",
 how:"The Linux route is fully testable here: spreadsheet to print-ready PDF with HTML and CSS (WeasyPrint or Paged.js) or Typst. If the client must edit in InDesign, Claude writes the script and the client runs it.",
 where:"Adobe's InDesign community, Upwork \"catalog automation\" and \"data merge\" jobs, local print shops (as white-label work), marketing managers at distributors.",
 first:"Build a 16-page demo catalogue from a public sample product file, then pitch a fixed-price setup to 10 print shops and 10 distributors.",
 risk:"Font and image licences, print specs (bleed, CMYK), and costly price typos once printed. Get written sign-off before anything goes to print."},
{id:"revit", group:"software", rank:106, s:[4,4,3,2],
 name:"Revit automation scripts",
 short:"pyRevit and Dynamo tools for architecture firms",
 who:"Architecture and engineering firms, BIM managers and building-services contractors.",
 need:"Batch sheet and view creation, schedules to and from Excel, model checks, and placing components from spreadsheets.",
 demand:"ZipRecruiter lists Revit/Dynamo and Revit API jobs through 2026, and BIM-manager roles paying $130,000–160,000 mention managing custom tools.",
 why:"Cad Crowd lists only 28 Revit Dynamo freelancers (May 2026), and specialists earn more because the skill is scarce.",
 price:"$30–95 an hour",
 how:"Claude writes pyRevit Python and tests the pure logic here. Revit only runs on Windows, so the client runs each tool on a detached copy of the model, or you use a Windows PC with a Revit trial.",
 where:"forum.dynamobim.com, the pyRevit forum, Autodesk's Revit API forum, BIM managers on LinkedIn, Cad Crowd.",
 first:"Publish one free pyRevit tool (sheets to and from Excel), post it on the pyRevit and Dynamo forums, and offer 10 BIM managers a free first script in exchange for a testimonial.",
 risk:"Scripts can damage models, so only work on detached copies. Don't use student licences for paid work."},
{id:"edi", group:"software", rank:107, s:[4,3,4,2],
 name:"EDI files for small brands selling to big retailers",
 short:"Orders, shipping notices and invoices in the retailer's format",
 who:"Small brands newly selling to Walmart, Target, Home Depot and similar chains, and small logistics firms.",
 need:"Translating purchase orders (850), shipping notices (856) and invoices (810) between the retailer's EDI system and the brand's spreadsheets, Shopify or QuickBooks.",
 demand:"Big retailers require these documents, and a missing or late shipping notice can cost $200–2,000+ per shipment in penalties. One small team was quoted about $8,000 by an established vendor, and EDI services run $100–1,000+ a month.",
 why:"Searches turned up vendors and consultancies, not freelancers working at small-business prices (unverified).",
 price:"$500–3,000 per retailer connection (est.)",
 how:"Claude reads the retailer's specification PDF and writes code that generates and validates the files, tested here against the spec's samples. Sending files and retailer certification go through the client's EDI provider.",
 where:"Brands announcing new big-retail deals, operations managers on LinkedIn, logistics communities. Search: \"Walmart 856 ASN\", \"EDI mapping help\".",
 first:"Build a spreadsheet-to-shipping-notice (856) generator checked against a public retailer spec, and offer a free error check to 10 newly listed brands.",
 risk:"Penalties fall on the client, so cap your liability and never guarantee compliance. Keep their pricing data confidential."}
);
