// Hidden niches: demand with evidence, few providers, and work Claude can do (research, Oct 2026).
// s = [demand, few competitors, Claude fit, beginner-friendly], each 1-5.
var NICHE_GROUPS = {
  rules:"Rules and deadlines",
  software:"Specialist software",
  backoffice:"Back office",
  data:"Data subscriptions",
  requests:"Things people ask for",
  aiera:"New AI needs",
  research:"Research and nonprofits",
  crossborder:"Cross-border selling"
};
var NICHES = [];

// --- Specialist software
NICHES.push(
{id:"access-rescue", group:"software", rank:101, s:[4,4,4,3],
 name:"Microsoft Access database rescue",
 short:"Keep old Access databases running, or move them to the web",
 who:"Small manufacturers, clinics, distributors, charities and councils whose Access database was built by someone who has since left.",
 need:"Fixes after Office updates, new reports, 64-bit VBA fixes, or moving the data into a proper database or a web app.",
 demand:"Access 2021 support ends on 13 October 2026, a year after Access 2016 and 2019. US Access/VBA work averages about $48 an hour (ZipRecruiter, Aug 2026), and London contracts have a median of £650 a day.",
 why:"Migration firms all report the same thing: the original builder has often retired, and VBA skills get harder to find every year.",
 price:"$150–600 per fix, $1,500–8,000 per migration",
 how:"Python tools (mdbtools, access-parser) read the tables here. The client exports forms and VBA as text so Claude can read every module. A web replacement can be built and fully tested in this sandbox; VBA changes have to be tested by the client on Windows.",
 where:"UtterAccess, Access World Forums, r/MSAccess, Microsoft Q&A, Upwork \"Microsoft Access\" jobs, and local IT-support firms that inherit these databases.",
 first:"Turn Microsoft's free Northwind sample database into a small web app, publish a before-and-after page, and offer a $99 \"Access health check\" to 15 job posts and 10 local IT firms.",
 risk:"These files hold personal data, so sign an NDA, work on copies and delete them afterwards. Never edit the live file."},
{id:"drupal7", group:"software", rank:102, s:[4,3,5,3],
 name:"Getting organisations off Drupal 7",
 short:"Upgrade, archive or migrate sites on an unsupported system",
 who:"Nonprofits (often using CiviCRM), university departments, associations and councils.",
 need:"A safe, affordable way off Drupal 7: upgrade to Backdrop (a Drupal 7 fork), freeze the site as static pages, or migrate to current Drupal, plus a malware check.",
 demand:"Drupal 7 support ended on 5 January 2025, yet about 134,000 sites reportedly still run it (unverified). Organisations pay for extended security support through the Drupal Association's paid program.",
 why:"Agencies price these moves at £4,000–35,000. Very little is offered at small-budget prices.",
 price:"$800–3,000 per fixed package (est.)",
 how:"Everything can be tested here: run a copy of the client's site in Docker, run Backdrop's upgrade or Drupal's migration, and compare old and new pages with Playwright screenshots. A static archive is just a crawl of the site.",
 where:"The CiviCRM community, Drupal Slack, university web teams, and sites whose page source still shows the \"Generator: Drupal 7\" tag.",
 first:"Move a sample Drupal 7 site to Backdrop and to a static archive here, write a one-page \"3 ways off Drupal 7\" PDF, and email 20 nonprofits still running it.",
 risk:"Many of these sites are already hacked, so scan copies before moving them. Only look at what a normal visit shows, and follow cold-email laws."},
{id:"autolisp", group:"software", rank:103, s:[3,4,4,3],
 name:"AutoCAD automation routines (AutoLISP)",
 short:"Small scripts that save drafters hours every week",
 who:"Small drafting, building-services, survey, civil and fabrication firms, and their CAD managers.",
 need:"Batch layer and block edits, auto-numbering, exporting attributes or coordinates to Excel, standard details and standards checks.",
 demand:"Autodesk's forums carry repeated \"hiring a LISP programmer\" threads, and ZipRecruiter lists AutoLISP jobs at $25–49 an hour (Jun 2026). AutoCAD LT gained AutoLISP in 2024, opening up its large base of cheaper users.",
 why:"Cad Crowd lists only 28 AutoLISP freelancers (Mar 2026). Forum volunteers write tiny routines for free, so sell bundles rather than one-liners.",
 price:"$50–300 per routine, $500–1,500 per project",
 how:"Claude writes AutoLISP well, and the Python ezdxf library builds and checks test drawings here. AutoCAD doesn't run on Linux, so the client does the final test (a BricsCAD trial works for a first check).",
 where:"The Visual LISP forum on forums.autodesk.com, CADTutor, TheSwamp, AUGI, Cad Crowd, Upwork \"AutoLISP\" jobs, CAD managers on LinkedIn.",
 first:"Publish 3 free routines that work in AutoCAD LT, answer 3 forum requests with them, and offer 15 CAD managers one custom routine for $99.",
 risk:"Don't reuse other people's copyrighted routines, and test only on copies of drawings."},
{id:"coldfusion", group:"software", rank:104, s:[3,5,4,2],
 name:"ColdFusion maintenance and moves to Lucee",
 short:"Keep 20-year-old business apps alive and secure",
 who:"Insurers, government bodies, universities and membership groups running old ColdFusion apps for billing, claims or licensing.",
 need:"Bug and security fixes, moving from paid Adobe ColdFusion to the free Lucee engine, upgrades and documentation.",
 demand:"Vendors report that many organisations still run mission-critical ColdFusion apps in 2026, and companies keep advertising ColdFusion roles.",
 why:"Ortus calls it a \"CFML talent crunch\": experienced developers are shrinking fast and many companies depend on a single developer.",
 price:"$60–125 an hour (est.)",
 how:"CommandBox and Lucee run on Linux, so a copy of the app runs here against a copy of its database. Claude fixes SQL injection, updates old tags and writes tests; Adobe-only features are tested on the client's staging server.",
 where:"CFML Slack, dev.lucee.org, Adobe's ColdFusion community, ColdFusion contracts on LinkedIn, Dice and Indeed.",
 first:"Move a small open-source ColdFusion app to the latest Lucee, publish the write-up, and send it to 10 organisations advertising ColdFusion roles.",
 risk:"Cautious buyers may ask for background checks or insurance. Say plainly that the work is AI-assisted and human-reviewed, and never test on the live system."},
{id:"catalogue", group:"software", rank:105, s:[3,3,4,4],
 name:"Spreadsheet-to-catalogue automation",
 short:"Print-ready product catalogues rebuilt from a spreadsheet",
 who:"Wholesalers, parts distributors, furniture and fashion brands, and print shops that produce seasonal price lists.",
 need:"A product spreadsheet and photos turned into a styled multi-page catalogue that can be re-run whenever prices change.",
 demand:"Adobe forum users keep asking how to automate catalogues from Excel, and a market of paid plugins exists for it (EasyCatalog, InData and others).",
 why:"InDesign's built-in Data Merge can't handle complex multi-page layouts, so the job needs scripting, which few designers do.",
 price:"$300–2,500 per setup, plus a fee per new edition (est.)",
 how:"The Linux route is fully testable here: spreadsheet to print-ready PDF with HTML and CSS (WeasyPrint or Paged.js) or Typst. If the client must edit in InDesign, Claude writes the script and the client runs it.",
 where:"Adobe's InDesign community, Upwork \"catalog automation\" and \"data merge\" jobs, local print shops (as white-label work), marketing managers at distributors.",
 first:"Build a 16-page demo catalogue from a public sample product file, then pitch a fixed-price setup to 10 print shops and 10 distributors.",
 risk:"Font and image licences, print specs (bleed, CMYK), and costly price typos once printed. Get written sign-off before anything goes to print."},
{id:"revit", group:"software", rank:106, s:[4,4,3,2],
 name:"Revit automation scripts",
 short:"pyRevit and Dynamo tools for architecture firms",
 who:"Architecture and engineering firms, BIM managers and building-services contractors.",
 need:"Batch sheet and view creation, schedules to and from Excel, model checks, and placing components from spreadsheets.",
 demand:"ZipRecruiter lists Revit/Dynamo and Revit API jobs through 2026, and BIM-manager roles paying $130,000–160,000 mention managing custom tools.",
 why:"Cad Crowd lists only 28 Revit Dynamo freelancers (May 2026), and specialists earn more because the skill is scarce.",
 price:"$30–95 an hour",
 how:"Claude writes pyRevit Python and tests the pure logic here. Revit only runs on Windows, so the client runs each tool on a detached copy of the model, or you use a Windows PC with a Revit trial.",
 where:"forum.dynamobim.com, the pyRevit forum, Autodesk's Revit API forum, BIM managers on LinkedIn, Cad Crowd.",
 first:"Publish one free pyRevit tool (sheets to and from Excel), post it on the pyRevit and Dynamo forums, and offer 10 BIM managers a free first script in exchange for a testimonial.",
 risk:"Scripts can damage models, so only work on detached copies. Don't use student licences for paid work."},
{id:"edi", group:"software", rank:107, s:[4,3,4,2],
 name:"EDI files for small brands selling to big retailers",
 short:"Orders, shipping notices and invoices in the retailer's format",
 who:"Small brands newly selling to Walmart, Target, Home Depot and similar chains, and small logistics firms.",
 need:"Translating purchase orders (850), shipping notices (856) and invoices (810) between the retailer's EDI system and the brand's spreadsheets, Shopify or QuickBooks.",
 demand:"Big retailers require these documents, and a missing or late shipping notice can cost $200–2,000+ per shipment in penalties. One small team was quoted about $8,000 by an established vendor, and EDI services run $100–1,000+ a month.",
 why:"Searches turned up vendors and consultancies, not freelancers working at small-business prices (unverified).",
 price:"$500–3,000 per retailer connection (est.)",
 how:"Claude reads the retailer's specification PDF and writes code that generates and validates the files, tested here against the spec's samples. Sending files and retailer certification go through the client's EDI provider.",
 where:"Brands announcing new big-retail deals, operations managers on LinkedIn, logistics communities. Search: \"Walmart 856 ASN\", \"EDI mapping help\".",
 first:"Build a spreadsheet-to-shipping-notice (856) generator checked against a public retailer spec, and offer a free error check to 10 newly listed brands.",
 risk:"Penalties fall on the client, so cap your liability and never guarantee compliance. Keep their pricing data confidential."}
);

// --- Data subscriptions
NICHES.push(
{id:"epr-digest", group:"data", rank:201, s:[4,3,5,3],
 name:"Packaging-law updates for small consumer brands",
 short:"A monthly brief on US packaging fee laws and deadlines",
 who:"Food, drink, cosmetics, pet and home-goods brands with roughly $1M–50M in revenue, plus packaging distributors who could resell it to their clients.",
 need:"A monthly brief on what changed in state packaging \"producer responsibility\" (EPR) laws, which states apply to them and what is due when, with official links and a deadline calendar.",
 demand:"Seven US states now have packaging EPR laws. Oregon has invoiced since July 2025, Colorado's fees began in January 2026, and California's rules took effect in May 2026. Typical fees run $5,000–25,000 a year, and brands already pay compliance firms for help.",
 why:"Today's supply is free law-firm alerts written for big clients and enterprise compliance services. No low-cost recurring brief aimed at small brands turned up in the research (unverified).",
 price:"$39–99 a month per brand, or $300–800 a month white-label (est.)",
 how:"A weekly job checks about 30 official pages (state agency pages, the producer organisation's notices, bill trackers) for changes. Claude drafts the change notes and updates the deadline table; you check every line against its source. A scheduled Routine can run the weekly check.",
 where:"Operations and packaging people at consumer brands on LinkedIn, Shopify and DTC founder communities, packaging distributors. Search: \"EPR compliance small business\", \"SB 54 producer\".",
 first:"Write \"Packaging EPR status, October 2026\" for one product type (for example coffee roasters), send it to 30 founders and 5 packaging distributors with a $39 founding offer, and count the replies.",
 risk:"This must not become legal advice: describe the rules, never tell a client whether they owe fees. Summarise law-firm alerts in your own words rather than copying them."},
{id:"bid-digest", group:"data", rank:202, s:[4,3,4,4],
 name:"Public-bid digest for one trade, with past winning prices",
 short:"Every local government bid in one trade, plus who won before and at what price",
 who:"Small contractors in one trade (cleaning, mowing, paving, roofing, pest control) who bid on city, county and school work in one metro area or state.",
 need:"Every open bid in their trade, including small agencies, with scope, site-visit dates and insurance rules, plus the past results (\"bid tabulations\") showing who won and at what price.",
 demand:"Contractors already pay for bid alerts: BidNet Direct costs $599 a year for one state and BidPrime starts at $99 a month. Spending-data tools like GovSpend run $8,500–24,750 a year.",
 why:"Generic bid alerts are crowded, including new AI tools, so don't compete there. What nobody seems to package is a trade-specific digest with past winning prices from the agencies' own PDFs (weak evidence).",
 price:"$49–149 a month per contractor (est.)",
 how:"Keep a list of 50–150 agency bid pages plus the federal SAM.gov API. Each week Claude pulls the scope and dates out of the bid PDFs and turns past results into a price table; you check every deadline. Deliver a Monday email plus a spreadsheet.",
 where:"Firms named on past bid results (public business information), state trade associations, the cleaning industry's ISSA, builders' exchanges. Search: \"janitorial bids [state]\".",
 first:"Pick one trade and one metro, collect the open bids and 12 months of past results from 8 agencies, and email 30 firms named in those results offering 4 free weeks.",
 risk:"A wrong deadline is costly, so double-check them. Portals that need a login usually forbid redistribution, so link to notices instead of reposting them."},
{id:"council-watch", group:"data", rank:203, s:[4,3,5,3],
 name:"Local-government meeting watch for one industry",
 short:"Weekly brief on rezonings, moratoria and votes that affect a client's projects",
 who:"Small developers and land brokers (self-storage, car washes, solar and battery storage, data centres), commercial real-estate brokers, and contractors who want early warning.",
 need:"A weekly brief on relevant agenda items, rezonings, moratoria, votes and hearing dates across 10–40 councils and planning boards, with page references.",
 demand:"Startups raised money to do this (Hamlet raised $10M), and local rules are moving fast: one tracker counts 321 data-centre moratoriums or restrictions across 32 states as of September 2026.",
 why:"The existing players are venture-funded, sell through sales calls, hide their prices and cover the whole country. An affordable, human-checked brief for one industry wasn't found (unverified).",
 price:"$150–500 a month per client (est.)",
 how:"Pull agendas from public agenda systems (many councils use Legistar, which has a public API). Claude reads the meeting packets, flags relevant items and summarises them with page numbers; you check each one. Deliver a Monday email plus a status tracker.",
 where:"Development managers, land-acquisition and site-selection roles on LinkedIn, state solar and storage associations, CCIM and NAIOP chapters.",
 first:"Pick one industry and one state (for example battery storage in Ohio), build a 30-day digest covering 10–20 counties, and send it to 25 development managers with a $150 pilot offer.",
 risk:"A misreported vote destroys trust, so cite page numbers. Use official minutes, and remove residents' names from public comments."},
{id:"aid-tenders", group:"data", rank:204, s:[3,3,5,4],
 name:"International aid tenders for one specialty and language",
 short:"Filtered World Bank, UN and EU calls for small consultancies",
 who:"Small consultancies and freelancers in one specialty (evaluation, GIS, training, translation), especially French, Portuguese or Arabic-speaking ones.",
 need:"A weekly filtered list of tenders and calls from development banks, UN agencies and the EU, with plain summaries of each terms of reference.",
 demand:"People already pay for broad versions: Devex Pro costs $33–59 a month, and the UN Global Marketplace sells a tender alert service.",
 why:"The aggregators are broad and mostly in English, so users filter everything themselves. Curation by specialty and language is the gap (unverified). The market shrank after USAID's 2025 shutdown.",
 price:"$15–40 a month for individuals, $100–300 for firms (est.)",
 how:"Collect official procurement notices (World Bank, EU Funding & Tenders, development-bank and UNDP pages), and check each source's reuse terms. Claude sorts notices by specialty and summarises or translates the documents; you check them.",
 where:"Evaluation groups on LinkedIn, national and regional evaluation societies, the Devex community. Search: \"M&E consultancy tender\", \"appel d'offres évaluation\".",
 first:"Compile two weeks of evaluation tenders for one region and language, post it on LinkedIn and two professional mailing lists, and offer a €10-a-month founding price.",
 risk:"Don't resell paid alert services' listings, and link to tender documents instead of redistributing them. Aid budgets are shrinking."},
{id:"premises-digest", group:"data", rank:205, s:[3,3,4,4],
 name:"New commercial premises list for local service firms",
 short:"Weekly list of new commercial buildings and fit-outs in one metro",
 who:"Commercial cleaners, sign makers, alarm and security firms, IT cabling and fire-protection firms, commercial insurance brokers.",
 need:"A weekly list of new commercial buildings and tenant fit-outs (business, address, project value, contractor, stage) so they can pitch before the business opens.",
 demand:"National permit-data tools charge $599–999 a month for self-serve access, and lead publishers sell weekly permit editions.",
 why:"National data is priced for analysts, and raw scrapers need technical skill. Done-for-you local lists for service businesses look rare (unverified).",
 price:"$79–199 a month per metro (est.)",
 how:"Many US cities publish permits as open data. Filter for commercial and fit-out permits above a set value; Claude classifies each project and finds the business's website; you check the list. Deliver an email plus a spreadsheet.",
 where:"Business networking (BNI) chapters, chambers of commerce, ISSA, LinkedIn. Search: \"commercial construction leads [city]\".",
 first:"Pull four weeks of commercial permits from one city's open-data portal, build a sample list and call 20 local cleaning and sign firms.",
 risk:"Leave out residential permits, because homeowners are private individuals. Check each portal's licence before reusing its data."}
);

// --- New AI needs
NICHES.push(
{id:"model-retirement", group:"aiera", rank:301, s:[4,4,5,3],
 name:"Rescuing AI features before their model is retired",
 short:"Move a company's AI feature to a current model and prove it still works",
 who:"Small software companies, agencies and non-technical owners whose AI feature was built in 2023–25, often by a contractor who has left, and is tied to an old model version.",
 need:"Find every place the old model is used, switch to its successor, re-tune the prompts, and show with a before-and-after report that quality and cost are still fine.",
 demand:"Providers retire models on fixed dates and calls to a retired model simply fail. OpenAI is reported to shut down several older GPT-4-era models on 23 October 2026 (check OpenAI's deprecations page), and Anthropic's own retirement page lists an older Claude model ending on 30 November 2026, after nine retirements between October 2025 and August 2026. Newer models can also reject old settings and count tokens differently, so a simple name swap can break things or raise costs.",
 why:"Searches found no freelancers offering this as a service, only official guides written for developers. Companies without engineers have no obvious person to call (unverified).",
 price:"$300–800 per feature; $1,500–4,000 for a whole app with a reusable test set (est.)",
 how:"Claude Code finds and patches the model calls, builds a set of test cases from real (redacted) inputs, and runs old and new models side by side while the old one still works, producing a spreadsheet comparison. The client tests in staging with their own API key.",
 where:"Deprecation threads in the providers' developer forums (answer questions, don't spam), Bubble, FlutterFlow and WordPress-plugin communities, and agencies that sold AI bots in 2023–24. Search: \"model deprecated\", \"model shutdown\".",
 first:"Publish a one-page \"model shutdown checklist + fixed-price fix\", list it as a gig, and message 15 agencies and no-code builders. A good sign is 2 replies or 1 job within 72 hours.",
 risk:"You touch production code, so use branches and staging. Never use Claude to generate training data for other models. After a shutdown date the work becomes urgent, and you can get blamed for breakage."},
{id:"support-content", group:"aiera", rank:302, s:[4,3,5,4],
 name:"Fixing help-centre content so AI support bots stop failing",
 short:"Rewrite the articles that make AI support agents give wrong answers",
 who:"Support leads at companies with 5–50 support agents who pay per ticket their AI bot resolves (Intercom Fin, Zendesk AI, Gorgias) and see too many escalations.",
 need:"Analysis of the conversations the bot failed, then fixes for missing, contradictory, stale and duplicate help articles, plus a monthly gap report.",
 demand:"Intercom reports Fin resolves 56% of conversations on average in its first 30 days, with some customers near 90%, and blames wrong answers on outdated or conflicting articles. Intercom even built a dashboard that flags content gaps, which shows content is the bottleneck.",
 why:"Freelancers in AI support sell bot setup, not knowledge-base work. The vendors' auto-drafted articles still need a person to check the facts.",
 price:"$1,000–3,500 for an audit plus 40–120 articles; $400–1,000 a month for upkeep (est.)",
 how:"Claude groups an export of unresolved conversations by theme, finds contradictions and rewrites articles in the brand's voice, with a spreadsheet change log. The support lead checks policy facts and tests in the bot's preview mode.",
 where:"Intercom and Zendesk communities, Support Driven Slack, \"Head of Support\" and \"CX Ops\" roles on LinkedIn. Search: \"Fin resolution rate\", \"knowledge base audit\".",
 first:"Do a free \"contradictions and gaps\" teardown of one public help centre that has an AI chat widget, and send it to 5 support leads with a fixed price. A good sign is 1 call booked.",
 risk:"Wrong policy text creates liability, so the client signs off every article. Ask for exports with personal data removed."},
{id:"ai-evals", group:"aiera", rank:303, s:[4,3,5,3],
 name:"Test suites for small teams' AI features",
 short:"Automatic checks that an AI feature still answers correctly after every change",
 who:"Early-stage startups and agencies shipping AI features with no quality testing.",
 need:"50–300 test cases with scoring rules, automated runs on every prompt or model change, a safe pack of misuse tests (prompt injection, data leaks, promises the bot shouldn't make), and a scorecard.",
 demand:"In LangChain's survey of 1,300+ practitioners, 57% have AI agents in production and 32% call quality the top barrier, but only 52% run evaluations. Contract AI testers earn $40–90 an hour.",
 why:"Supply is mostly self-serve tools and lab data-labelling gigs. Only about 9 evaluation gigs turned up on Fiverr, while chatbot-building gigs are saturated.",
 price:"$750–3,000 setup, plus $200–800 a month for regular runs (est.)",
 how:"Claude drafts test cases from the client's docs and transcripts, writes the scoring rules, and builds and runs the test harness (open-source tools like promptfoo) against the client's system using their key. You check the automated grader against about 30 answers graded by hand.",
 where:"LangChain and LlamaIndex communities, Indie Hackers, AI launches on Product Hunt, Upwork \"LLM testing\" jobs.",
 first:"Ask 3 public website bots 20 ordinary customer questions (no attacks), and send each owner an accuracy report with an offer. A good sign is 1 request.",
 risk:"Run misuse tests only with the owner's written permission. Sign an NDA for transcripts, and never use the test data to train models."},
{id:"claude-skill-packs", group:"aiera", rank:304, s:[3,3,5,4],
 name:"Custom Claude skill packs for small teams",
 short:"Skills built on a firm's own templates, delivered as a private plugin",
 who:"Agencies, accounting firms and consultancies of 5–150 people on Claude's Team plan who get generic output.",
 need:"3–8 tested skills built on the firm's own templates and rules (proposals with their pricing, monthly client reports from their exports), packaged as a private plugin with a short training session.",
 demand:"Skills launched in October 2025, organisation-wide management followed in December, and private plugin marketplaces arrived in February 2026. Direct job posts from small firms weren't found yet (unverified).",
 why:"Anthropic's named plugin partners serve large enterprises, and only about 4 Fiverr sellers offer this. Anthropic's free templates cover generic needs, so sell skills built on the client's own material.",
 price:"$250–600 per skill; $1,500–4,000 per team pack (est.)",
 how:"Claude's skill-creator drafts the skill files, scripts and document templates and tests them against the client's real samples. The client's admin installs the pack.",
 where:"LinkedIn demo posts, agency-owner groups, businesses posting about adopting Claude. Search: \"Claude Team plan\", \"Cowork plugin\".",
 first:"Build one demo skill for one industry, post a 2-minute before-and-after video, and message 10 owners who post about Claude. A good sign is 2 demo requests.",
 risk:"Deliver files, never share accounts. Skills that touch HR, legal or finance decisions need a qualified person's review."},
{id:"ai-ready-docs", group:"aiera", rank:305, s:[4,3,4,3],
 name:"Cleaning up company documents before an AI rollout",
 short:"Find duplicates, stale versions and over-shared files so the AI gives right answers",
 who:"Small and mid-size firms rolling out Copilot, Claude, ChatGPT or Notion AI over messy shared drives.",
 need:"An inventory of documents with duplicates and stale versions flagged, one current page per topic with an owner, and a list of over-shared sensitive files for their admin.",
 demand:"Gartner found 63% of organisations lack, or aren't sure they have, data practices suited to AI, and predicts many AI projects will be abandoned for lack of AI-ready data. IT firms sell Copilot oversharing fixes starting around $4,950.",
 why:"IT service firms sell permission fixes; the content clean-up itself is rarely sold on its own (unverified).",
 price:"$1,500–5,000 per department (est.)",
 how:"Claude reads exported Word, PDF and Excel files, groups duplicates, finds contradictions and drafts the current pages, producing a keep/merge/archive spreadsheet and a list of permission risks. The client's admin makes the changes.",
 where:"Managed IT providers (as white-label work, which suits zero reviews), Microsoft 365 and Notion consultant communities. Search: \"Copilot readiness\", \"SharePoint cleanup\".",
 first:"Email 5 local IT providers offering a content clean-up add-on, with a sample built from a public company's published policies. A good sign is 1 pilot.",
 risk:"The documents are confidential: sign an NDA and keep model training off. Never change permissions yourself."},
{id:"ai-policy-pack", group:"aiera", rank:306, s:[3,3,4,3],
 name:"AI transparency and staff AI-use packs",
 short:"Tool inventory, staff policy, disclosure wording and training for small firms",
 who:"EU-facing agencies, publishers and shops that use chatbots or publish AI content, and small businesses with no AI policy.",
 need:"An inventory of AI tools, a staff AI-use policy, disclosure wording for chatbots and AI-generated content, and short staff training with an attendance log.",
 demand:"The EU AI Act's transparency rules (Article 50) have applied since 2 August 2026, with large fines possible. In one survey of 4,400 small and mid-size firms, 81% use AI but only 69% have a policy.",
 why:"Law firms are expensive and templates are free, but hands-on help for 10–50 person firms looks thin (unverified).",
 price:"€500–2,000 per pack; €150–400 per training session (est.)",
 how:"Claude drafts the policy, disclosure wording, a slide deck and a quiz with an attendance log. A partner lawyer reviews it, because legal interpretation needs a qualified person.",
 where:"Chambers of commerce, agency networks, LinkedIn. Search: \"AI Act Article 50\", \"AI policy template\".",
 first:"Find a lawyer willing to review, publish a free Article 50 checklist, and offer 3 discounted pilots. A good sign is 1 pilot.",
 risk:"This is not legal advice and the rules keep moving. Don't sell with exaggerated fine threats."},
{id:"ai-cost-audit", group:"aiera", rank:307, s:[4,3,4,2],
 name:"AI API bill audits for startups",
 short:"Cut a startup's AI model bill without hurting quality",
 who:"Startups spending roughly $2,000–50,000 a month on AI model APIs.",
 need:"Spend broken down by feature and model, savings from prompt caching, batching, smaller models and output limits, and proof that quality held.",
 demand:"Industry write-ups put AI running costs at about 23% of revenue for growing AI firms, with gross margins of 50–60% against 80–90% for normal software. Anthropic charges a tenth of the input price for cached reads and half price for batch requests, and the discounts stack.",
 why:"Cost consultancies focus on cloud bills and AI gateway tools are self-serve. Few freelancers sell a fixed-price audit (unverified).",
 price:"$1,000–3,000, or 20–30% of verified savings over 3 months (est.)",
 how:"Claude analyses the usage export by key and model and patches the code for caching and batching, then proves quality with a test set (see the AI test suites niche). The client deploys.",
 where:"Indie Hackers, founders complaining about API bills on X, startup Slack and Discord groups.",
 first:"Publish a savings-calculator page and offer 3 free audits in exchange for testimonials. A good sign is 3 sign-ups.",
 risk:"Cheaper setups can lower quality, so measure savings rather than promising them. Technical buyers expect credibility."},
{id:"chatgpt-ads", group:"aiera", rank:308, s:[4,3,3,2],
 name:"ChatGPT Ads setup for small US businesses",
 short:"Launch and manage campaigns on a five-month-old ad channel",
 who:"US small businesses and online brands testing ChatGPT's new ad platform.",
 need:"Conversion tracking, campaign structure, ad copy variants, matching landing pages and weekly reports.",
 demand:"OpenAI opened self-serve Ads Manager to all US businesses in 2026 with cost-per-click bidding and no minimum spend; trade press reports clicks around $3–5. The named agency partners are giant holding companies that skip small budgets.",
 why:"The channel is new, but about 8 Fiverr gigs already exist, some from ad specialists with 1,000+ orders, so the window is closing.",
 price:"$300–700 setup plus $300–1,000 a month (est.)",
 how:"Claude writes ad copy variants, maps buyer questions to ads, edits landing pages and analyses report exports. You run Ads Manager and control budgets by hand.",
 where:"Shopify merchant communities, local business groups. Search: \"ChatGPT ads\", \"OpenAI Ads Manager\".",
 first:"Run a $50–100 campaign for your own page, publish a 7-day write-up of the results, and pitch 10 businesses. A good sign is 1 quote request.",
 risk:"You handle client money and results are hard to attribute. US-only for now, and you compete with experienced ad specialists."}
);
